import asyncio, json
import pathlib
from playwright.async_api import async_playwright
PROTO = pathlib.Path(__file__).with_name('BRAC_Nirapatta_Prototype.html').resolve().as_uri()
R=[]
def check(id_, name, cond, detail=''):
    R.append((id_, name, 'PASS' if cond else 'FAIL', detail)); 
async def kpis(pg):
    await pg.click('[data-wact="page"][data-v="overview"]')
    return await pg.evaluate("[...document.querySelectorAll('.kpi .v')].map(e=>+e.textContent)")
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch()
        ctx = await b.new_context(viewport={'width':1600,'height':900}); pg = await ctx.new_page()
        errs=[]; pg.on('pageerror', lambda e: errs.append(str(e)))
        pg.on('dialog', lambda d: asyncio.ensure_future(d.accept()))
        await pg.goto(PROTO); await pg.wait_for_timeout(300)
        S = lambda js: pg.evaluate(f"(()=>{{const S=NIRAPATTA.state(),D=NIRAPATTA.D;return {js}}})()")
        # --- seed fidelity
        k = await kpis(pg); check('D-01','Seed KPIs = 2/18/47/6 (Picture_1)', k==[2,18,47,6], str(k))
        wk = await S("D.weekly()"); check('D-02','Weekly SOS 1,2,1,3,2,2,3 / Incidents 0,1,1,2,1,1,2', [w['sos'] for w in wk]==[1,2,1,3,2,2,3] and [w['inc'] for w in wk]==[0,1,1,2,1,1,2], json.dumps(wk))
        br = await S("D.byBranch()"); check('D-03','Branch chart Mirpur 8, Rajshahi 5, Feni Sadar 3, Uttara 6', [(x['branch'],x['n']) for x in br]==[('Mirpur',8),('Rajshahi',5),('Feni Sadar',3),('Uttara',6)], str(br))
        badge = await pg.inner_text('.m-header .badge'); check('D-04','Mobile bell badge shows 3', badge=='3')
        acts = await pg.evaluate("[...document.querySelectorAll('#liveActivity p')].map(p=>p.innerText.split('\\n')[0])")
        check('D-05','Live Activity seed matches Picture_1 order', acts[:3]==['SOS: Employee PIN 102934 requested assistance.','Incident: Road accident report submitted from Dhaka.','Broadcast: Travel advisory sent to 1,240 employees.'], str(acts))
        await pg.click('[data-wact="page"][data-v="users"]'); rows = await pg.evaluate("[...document.querySelectorAll('.dt tbody tr')].map(r=>r.cells[0].innerText.split('\\n')[0]+'|'+r.cells[1].innerText+'|'+r.cells[4].innerText.split('\\n')[0].replace(/Verify|Reject/g,'').trim())")
        check('D-06','Users table matches Picture_6', rows==['Md. Rahim|102934|Verified','Sharmin Akter|874022|Verified','Karim Hossain|—|Pending Verification'], str(rows))
        live = await pg.evaluate("(()=>{const d=new Date();const M=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];return d.getDate()+' '+M[d.getMonth()]+', '+d.getFullYear()})()")
        await pg.click('[data-wact="page"][data-v="sos"]'); first = await pg.inner_text('.dt tbody tr:first-child')
        check('DT-04','Seed SOS rows use today\'s date (no stale 28 Sep)', live in first, first.replace('\t',' | '))
        clk = await pg.inner_text('.w-clock'); check('DT-05','Dashboard clock shows today', str(await pg.evaluate("new Date().getFullYear()")) in clk, clk.replace('\n',' '))
        wait = await pg.inner_text('.dt tbody tr:first-child .wait'); check('UX-01','New SOS shows waiting time, red past 2-min target', 'Waiting 3 min' in wait and 'over 2-min target' in wait, wait)
        badge_sos = await pg.inner_text('.w-side [data-v="sos"] .side-badge'); check('UX-02','Sidebar badge counts unacknowledged SOS', badge_sos=='1', badge_sos)
        logo = await pg.evaluate("[...document.querySelectorAll('.brac-logo svg path')].length"); check('UX-03','BRAC logo mark (4 petals + ring) in phone, dashboard and footer', logo>=15, str(logo))
        await pg.click('[data-wact="page"][data-v="overview"]')
        # --- login
        await pg.fill('#f-pin','999999'); await pg.click('[data-act="verify"]')
        check('M-01','Unknown PIN shows error', 'No verified account' in await pg.inner_text('#screen'))
        await pg.fill('#f-pin','102934'); await pg.fill('#f-otp','12'); await pg.click('[data-act="verify"]')
        check('M-02','Short OTP shows error', 'Enter the 6-digit OTP' in await pg.inner_text('#screen'))
        await pg.fill('#f-otp','284913'); await pg.click('[data-act="verify"]'); await pg.wait_for_timeout(200)
        check('M-03','PIN+OTP login opens Health & Family modal', await pg.is_visible('#hTitle'))
        await pg.fill('#h4','12345'); await pg.click('[data-act="saveHealth"]')
        check('M-04','Invalid family phone rejected', 'valid Bangladesh mobile' in await pg.inner_text('#screen'))
        await pg.select_option('#h1','B+'); await pg.fill('#h2','Asthma'); await pg.fill('#h3','Abdul Karim (Father)'); await pg.fill('#h4','+880 1711-223344'); await pg.click('[data-act="saveHealth"]'); await pg.wait_for_timeout(200)
        prof = await S("S.profiles['102934']"); check('M-05','Health info saved', prof and prof['blood']=='B+' and prof['famPhone']=='+880 1711-223344', str(prof))
        check('M-06','Home shows employee card (Picture_3)', 'Md. Rahim Uddin' in await pg.inner_text('.profile-card') and 'PIN: 102934' in await pg.inner_text('.profile-card'))
        # --- SOS cancel
        await pg.click('#sosBtn'); await pg.wait_for_timeout(300)
        check('F-02a','SOS tap shows 3-second cancel countdown', await pg.is_visible('.countdown'))
        await pg.click('[data-act="cancelSos"]'); await pg.wait_for_timeout(3300)
        check('F-02b','Cancelled SOS sends nothing', (await S("S.sos.length"))==3)
        # Rahim already has seeded New SOS-0128 → second SOS escalates it (no duplicate)
        await pg.click('#sosBtn'); await pg.wait_for_timeout(3600)
        esc_ = await S("({n:S.sos.length, e:S.sos.find(s=>s.id==='SOS-0128').escalations})")
        check('F-02c','Repeat SOS escalates existing alert, no duplicate', esc_['n']==3 and esc_['e']==1, str(esc_))
        await pg.click('[data-wact="page"][data-v="sos"]')
        check('F-02c2','Escalated row shows ×2 badge at top', '×2' in await pg.inner_text('.dt tbody tr:first-child'))
        await pg.click('tr[data-v="SOS-0128"]'); await pg.wait_for_timeout(200)
        check('W-01','SOS drawer shows health & family data', 'Asthma' in await pg.inner_text('.drawer') and 'B+' in await pg.inner_text('.drawer'))
        await pg.click('[data-wact="sosResp"]'); await pg.wait_for_timeout(100)
        await pg.click('[data-wact="sosResolve"]'); check('W-02','Resolve without closure note blocked', 'closure note' in (await pg.inner_text('.drawer')).lower())
        await pg.fill('#closeNote','False alarm, employee safe.'); await pg.click('[data-wact="sosResolve"]'); await pg.wait_for_timeout(200)
        check('W-03','SOS resolved with note', (await S("S.sos.find(s=>s.id==='SOS-0128').status"))=='Resolved')
        await pg.keyboard.press('Escape')
        # --- real SOS from phone
        before = await kpis(pg)
        await pg.click('[data-act="go"][data-to="home"]'); await pg.click('#sosBtn'); await pg.wait_for_timeout(3600)
        after = await kpis(pg)
        check('F-02d','SOS from phone: Active SOS +1, Location Shares +1', after[0]==before[0]+1 and after[2]==before[2]+1, f'{before}->{after}')
        newest = await S("S.sos[0]"); check('F-02e','New SOS row has status New, PIN 102934', newest['status']=='New' and newest['pin']=='102934')
        check('F-02f','Live Activity logs SOS', 'Employee PIN 102934 requested assistance' in await pg.inner_text('#liveActivity'))
        check('F-02g','Phone shows "SOS sent" status card', 'SOS sent' in await pg.inner_text('#screen'))
        wk2 = await S("D.weekly()[6].sos"); check('F-02h','Weekly chart: today SOS bar increments to 4', wk2==4, str(wk2))
        # --- respond → phone sees it
        await pg.click('[data-wact="page"][data-v="sos"]'); await pg.click(f'tr[data-v="{newest["id"]}"]'); await pg.click('[data-wact="sosResp"]'); await pg.wait_for_timeout(200)
        check('F-03a','Officer responds → phone shows "responding"', 'responding to your SOS' in await pg.inner_text('#screen'))
        await pg.fill('#closeNote','Area manager reached the employee.'); await pg.click('[data-wact="sosResolve"]'); await pg.wait_for_timeout(200)
        check('F-03b','Officer resolves → phone shows resolved', 'has been resolved' in await pg.inner_text('#screen'))
        check('F-03c','Resolving SOS stops its auto location share', (await S("!!D.activeShare('102934')"))==False)
        await pg.keyboard.press('Escape')
        # --- simulate SOS
        n = await S("S.sos.length"); await pg.click('[data-wact="simulate"]'); await pg.wait_for_timeout(200)
        check('F-04','Simulate SOS adds row + toast', (await S("S.sos.length"))==n+1 and await pg.is_visible('.w-toast.sos'))
        # --- location share
        await pg.click('[data-act="go"][data-to="location"]'); await pg.click('[data-act="dur"][data-v="60"]'); sh0=(await kpis(pg))[2]
        await pg.click('[data-act="startShare"]'); await pg.wait_for_timeout(1200)
        timer = await pg.inner_text('[data-countdown]'); check('F-05a','Share starts with 1-hr countdown', timer.startswith('59:'), timer)
        check('F-05b','Location Shares KPI +1', (await kpis(pg))[2]==sh0+1)
        await pg.click('[data-act="stopShare"]'); check('F-05c','Stop sharing works', (await S("!!D.activeShare('102934')"))==False)
        # --- incident report
        oi=(await kpis(pg))[1]; mir=(await S("D.byBranch().find(b=>b.branch==='Mirpur').n"))
        await pg.click('[data-act="go"][data-to="report"]'); await pg.click('[data-act="submitReport"]'); await pg.wait_for_timeout(150)
        check('F-06x','Untouched pre-filled report submits (D2 regression)', (await S("S.incidents.length"))==23)
        await pg.click('[data-act="newReport"]'); await pg.fill('#desc',''); await pg.click('[data-act="submitReport"]')
        check('F-06a','Empty description blocked', 'describe what happened' in await pg.inner_text('#screen'))
        await pg.check('[data-f="behalf"]'); await pg.wait_for_timeout(100); await pg.click('[data-act="submitReport"]')
        await pg.wait_for_timeout(150); check('F-06b','On-behalf requires colleague name + PIN', 'name and PIN' in await pg.inner_text('.m-body'), (await pg.inner_text(".m-body")).replace("\n"," | ")[:400])
        await pg.fill('#c1','Shahidul Islam'); await pg.fill('#c2','417733'); await pg.select_option('#cat','Harassment'); await pg.fill('#desc','Staff followed after group meeting.')
        await pg.click('[data-act="rec"]'); await pg.wait_for_timeout(2100); await pg.click('[data-act="rec"]')
        check('F-06c','Voice note recorded & attached', 'Voice note attached' in await pg.inner_text('#screen'))
        await pg.click('[data-act="submitReport"]'); await pg.wait_for_timeout(200)
        ref = await pg.inner_text('.success-card .ref'); check('F-06d','Reference number shown', ref.endswith('-0024') and ref.startswith('NIR-INC-'), ref)
        check('F-06e','Open Incidents KPI +2, Mirpur bar +2 (two reports)', (await kpis(pg))[1]==oi+2 and (await S("D.byBranch().find(b=>b.branch==='Mirpur').n"))==mir+2)
        await pg.click('[data-wact="page"][data-v="incidents"]'); await pg.click('tr[data-v="NIR-INC-2026-0024"]')
        dr = await pg.inner_text('.drawer'); check('F-06f','Incident drawer shows on-behalf + voice note', 'Shahidul Islam' in dr and 'Attached' in dr)
        await pg.click('[data-wact="incStatus"]'); check('W-04','Incident status → In Review', (await S("S.incidents.find(i=>i.id==='NIR-INC-2026-0024').status"))=='In Review')
        await pg.keyboard.press('Escape')
        # --- broadcast
        await pg.click('[data-wact="page"][data-v="broadcast"]'); await pg.fill('#bMsg',''); await pg.click('[data-wact="send"]')
        check('F-07a','Empty broadcast blocked', 'Write the message' in await pg.inner_text('#web'))
        ub = await S("D.unreadFor('102934')")
        await pg.select_option('#bType','Weather Alert'); await pg.fill('#bMsg','Heavy rain in Dhaka tonight. Avoid low-lying roads.'); await pg.click('[data-wact="send"]'); await pg.wait_for_timeout(600)
        check('F-07b','Broadcast: Alerts Sent 7, phone badge +1, advisory updated', (await kpis(pg))[3]==7 and (await S("D.unreadFor('102934')"))==ub+1)
        await pg.click('[data-act="go"][data-to="home"]'); check('F-07c','Latest Advisory card updated on phone', 'Heavy rain in Dhaka' in await pg.inner_text('.advisory'))
        await pg.click('[data-act="go"][data-to="alerts"]'); await pg.wait_for_timeout(1700)
        check('F-07d','Opening Security Alerts clears badge', (await S("D.unreadFor('102934')"))==0)
        # --- language
        await pg.click('[data-act="lang"]'); txt = await pg.inner_text('#screen')
        await pg.click('[data-act="go"][data-to="alerts"]'); bnt = await pg.inner_text('.alert-item .t')
        check('DT-06','Bengali mode shows dates in Bengali digits and months', any(c in bnt for c in '০১২৩৪৫৬৭৮৯') and any(m in bnt for m in ['জানু','ফেব্রু','মার্চ','এপ্রিল','মে','জুন','জুলাই','আগস্ট','সেপ্টে','অক্টো','নভে','ডিসে']), bnt)
        await pg.click('[data-act="go"][data-to="home"]'); txt = await pg.inner_text('#screen')
        check('M-07','বাং switch translates mobile UI', 'নিরাপত্তা সতর্কবার্তা' in txt and 'হোম' in txt)
        await pg.click('[data-act="lang"]')
        # --- settings: theme keeps safety colours; mandatory info
        await pg.click('[data-act="go"][data-to="settings"]'); await pg.select_option('#s-theme','teal')
        acc = await pg.evaluate("getComputedStyle(document.querySelector('#screen')).getPropertyValue('--accent').trim()")
        safe = await pg.evaluate("getComputedStyle(document.querySelector('#screen')).getPropertyValue('--status-new-fg').trim()")
        check('F-09a','Theme changes accent only, safety red unchanged', acc=='#0F7C8C' and safe=='#C0262D', acc+' '+safe)
        await pg.select_option('#s-theme','magenta'); await pg.check('[data-set="requireHealth"]'); await pg.click('[data-act="signOut"]')
        check('F-09b','Sign out returns to Secure Login', 'Secure Login' in await pg.inner_text('#screen'))
        # Sharmin already has profile; use Abdul Karim (no profile)
        await pg.fill('#f-pin','556010'); await pg.fill('#f-otp','111111'); await pg.click('[data-act="verify"]'); await pg.wait_for_timeout(200)
        check('F-01a','Mandatory ON: no Skip / close on health modal', await pg.is_visible('#hTitle') and not await pg.is_visible('[data-act="skipHealth"]'))
        await pg.click('[data-act="saveHealth"]'); check('F-01b','Mandatory ON: empty family contact blocked', 'required' in await pg.inner_text('.m-modal'))
        await pg.fill('#h3','Rina Karim (Wife)'); await pg.fill('#h4','01812998877'); await pg.click('[data-act="saveHealth"]'); await pg.wait_for_timeout(200)
        check('F-01c','Mandatory ON: completes after valid entry', not await pg.is_visible('#hTitle'))
        check('D-07','PIN login auto-adds BRAC PIN user to Users', (await S("S.users.some(u=>u.pin==='556010' && u.reg==='BRAC PIN')")))
        await pg.click('[data-act="go"][data-to="settings"]'); await pg.click('[data-act="signOut"]')
        # --- self registration
        await pg.click('[data-act="go"][data-to="register"]'); await pg.click('[data-act="register"]')
        check('F-08a','Registration validates required fields', 'required' in await pg.inner_text('#screen'))
        await pg.fill('#r1','Popy Akter'); await pg.fill('#r2','01911223344'); await pg.fill('#r3','Rajshahi'); await pg.fill('#r6','123456'); await pg.click('[data-act="register"]'); await pg.wait_for_timeout(200)
        check('F-08b','Registration → pending message', 'pending verification' in (await pg.inner_text('#screen')).lower())
        await pg.click('[data-act="regback"]'); await pg.click('[data-act="ltab"][data-v="mobile"]'); await pg.fill('#f-mob','01911223344'); await pg.fill('#f-otp','123456'); await pg.click('[data-act="verify"]')
        check('F-08c','Pending user cannot sign in', 'still pending' in await pg.inner_text('#screen'))
        await pg.click('[data-wact="page"][data-v="users"]'); await pg.click('[data-wact="verify"][data-v="U-SR-002"]'); await pg.click('[data-act="verify"]'); await pg.wait_for_timeout(200)
        check('F-08d','After SCC verifies, user signs in with mobile', await pg.is_visible('#hTitle'))
        await pg.click('[data-act="skipHealth"] >> nth=-1') if await pg.is_visible('[data-act="skipHealth"]') else None
        # --- filters & search
        await pg.click('[data-wact="page"][data-v="sos"]'); await pg.select_option('[data-wf="sosStatus"]','Resolved')
        st = await pg.evaluate("[...document.querySelectorAll('.dt tbody .pill')].map(p=>p.textContent)"); check('W-05','Status filter shows only Resolved', len(st)>0 and set(st)=={'Resolved'}, str(st))
        await pg.select_option('[data-wf="sosStatus"]','all'); await pg.fill('.searchbar','874022')
        n2 = await pg.evaluate("document.querySelectorAll('.dt tbody tr.click').length"); check('W-06','Search by PIN filters table', n2==1, str(n2))
        await pg.fill('.searchbar','zzz'); check('W-07','No-match shows empty-state message', 'No SOS alerts match' in await pg.inner_text('.dt'))
        await pg.fill('.searchbar',''); await pg.wait_for_timeout(100)
        today_dmy = await pg.evaluate("(()=>{const d=new Date();return String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear()})()")
        await pg.click('#sosFromT'); await pg.keyboard.type(today_dmy.replace('/',''), delay=20); await pg.wait_for_timeout(200)
        shown = await pg.input_value('#sosFromT')
        check('DT-01','Typed date auto-formats to dd/mm/yyyy', shown==today_dmy, shown)
        n3 = await pg.evaluate("document.querySelectorAll('.dt tbody tr.click').length")
        check('W-08','Date filter (from today) hides yesterday\'s alert SOS-0126', n3>0 and not await pg.is_visible('tr[data-v="SOS-0126"]'), str(n3))
        await pg.click('#sosToT'); await pg.keyboard.type('01012020', delay=20); await pg.wait_for_timeout(200)
        check('DT-02','From after To shows a clear message', 'From date is after the To date' in await pg.inner_text('#web'))
        await pg.click('[data-wact="clearDates"]'); await pg.click('#sosFromT'); await pg.keyboard.type('31022026', delay=20); await pg.wait_for_timeout(150)
        check('DT-03','Impossible date 31/02/2026 is flagged, not applied', await pg.evaluate("document.querySelector('#sosFromT').closest('.daterange').classList.contains('bad')") and (await S("UI.w.sosFilter.from"))=='')
        await pg.click('[data-wact="clearDates"]') if await pg.is_visible('[data-wact="clearDates"]') else None
        await pg.fill('#sosFromT',''); await pg.wait_for_timeout(100)
        # --- consistency after everything
        cons = await S("({kpi:D.activeSos(), rows:S.sos.filter(s=>s.status!=='Resolved').length, inc:D.openIncidents(), incRows:S.incidents.filter(i=>i.status!=='Closed').length, br:D.byBranch().reduce((a,b)=>a+b.n,0), all:S.incidents.length})")
        check('D-08','Data consistency: KPIs = table rows, branch total = all incidents', cons['kpi']==cons['rows'] and cons['inc']==cons['incRows'] and cons['br']==cons['all'], str(cons))
        # --- persistence & reset
        await pg.reload(); await pg.wait_for_timeout(300)
        check('D-09','State persists after reload', (await S("S.incidents.length"))==24)
        await pg.click('[data-wact="dd"][data-v="user"]'); await pg.click('[data-wact="reset"]'); await pg.click('[data-wact="reset"]'); await pg.wait_for_timeout(300)
        check('D-10','Reset restores seed (2/18/47/6)', (await kpis(pg))==[2,18,47,6])
        # --- responsive
        for w in (1024, 390):
            await pg.set_viewport_size({'width':w,'height':900}); await pg.wait_for_timeout(200)
            ov = await pg.evaluate("document.documentElement.scrollWidth <= window.innerWidth+1")
            check(f'R-{w}', f'No horizontal page scroll at {w}px', ov)
            await pg.screenshot(path=f'screenshot_{w}px.png', full_page=False)
        check('E-01','No JavaScript errors during run', not errs, str(errs))
        await b.close()
    for r in R: print(' | '.join(r))
    print(f"\nTOTAL {len(R)}  PASS {sum(r[2]=='PASS' for r in R)}  FAIL {sum(r[2]=='FAIL' for r in R)}")
asyncio.run(main())
